services:
  redis:
    image: redis:8.2-m01-alpine3.22
    logging:
      driver: none
    attach: false
    ports:
      - "6379:6379"
    networks:
      - redis_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: none
    attach: false
    depends_on:
      - redis
    ports:
      - "8889:8889"
      - "8890:8890"
    networks:
      - redis_network
      - default
    dns:
      - 8.8.8.8
      - 1.1.1.1
    dns_search:
      - .

  k6:
    image: grafana/k6
    depends_on:
      - nginx
    volumes:
      - ./:/src
    entrypoint: ["k6", "run", "/src/k6.js"]
    networks:
      - default

networks:
  redis_network:
    driver: bridge
