services:
  redis:
    image: redis:8.2-m01-alpine3.22
    container_name: redis-cache
    ports:
      - "6379:6379"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "none"
    container_name: proxy
    depends_on:
      - redis
    ports:
      - "8889:8889"
      - "8890:8890"
  k6:
    image: grafana/k6
    depends_on:
      - nginx
    volumes:
      - ./:/src
    entrypoint: ["k6", "run", "/src/k6.js"]
