{
 "title": "Nginx Proxy Cache",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_deployment_spec_replicas,namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "deployment",
    "query": {
     "query": "label_values(kube_deployment_spec_replicas{namespace=\"$namespace\"},deployment)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(server_http_route_usage{namespace=\"$namespace\", deployment=\"$deployment\"},route)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_start_time{namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "cache_status",
    "label": "cache_status",
    "query": {
     "query": "label_values(nginx_http_cache_response_time_count{namespace=\"$namespace\", deployment=\"$deployment\"},cache_status)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Cache Time P50",
   "type": "heatmap",
   "description": "P50 (Mediana):\n\nDescrição: Este gráfico representa o valor da latência na mediana. Ou seja, 50% das requisições foram processadas mais rápido ou igual a este valor, e os outros 50% mais lentas. O P50 é uma boa medida para entender o desempenho central do sistema, pois não é influenciado por valores extremos.\nInterpretação: Ajuda a identificar o tempo de resposta típico do sistema para a maioria das requisições.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_http_cache_response_time_bucket{namespace=~\"$namespace\", deployment=~\"$deployment\", route=~\"$route\", pod_name=~\"$pod\", cache_status=~\"$cache_status\"}\n[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Server Cache Time P90",
   "type": "heatmap",
   "description": "P90 (Percentil 90):\n\nDescrição: Este gráfico mostra o valor da latência em que 90% das requisições foram processadas mais rápido ou igual a este tempo. Significa que os 10% mais lentos tiveram latências acima deste valor.\nInterpretação: É útil para entender o desempenho em relação às requisições mais lentas, ou seja, a \"cauda\" dos 10% mais lentos. Um aumento no P90 pode indicar problemas de desempenho que afetam uma parte significativa das requisições",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_http_cache_response_time_bucket{namespace=\"$namespace\", deployment=\"$deployment\", route=~\"$route\", pod=~\"$pod\", cache_status=~\"$cache_status\"}\n[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Server Cache Time P99",
   "type": "heatmap",
   "description": "P99 (Percentil 99):\n\nDescrição: Este gráfico representa o valor da latência em que 99% das requisições foram processadas mais rápido ou igual a este valor. Isso significa que apenas 1% das requisições são mais lentas do que o valor mostrado no gráfico.\nInterpretação: O P99 mostra a latência nos casos mais extremos do sistema, frequentemente usados para identificar outliers e entender o impacto dos piores casos no desempenho. A análise do P99 é importante para sistemas que precisam de alta confiabilidade, pois ele captura os momentos mais críticos.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_http_cache_response_time_bucket{namespace=\"$namespace\", deployment=\"$deployment\", route=~\"$route\", pod=~\"$pod\", cache_status=~\"$cache_status\"}\n[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "HTTP Cache",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  sum(rate(server_http_cache_status_total{namespace=~\"$namespace\", deployment=~\"$deployment\", cache_status=\"HIT\", route=~\"$route\", pod_name=~\"$pod\"}[$__rate_interval])) \n  /\n  sum(rate(server_http_cache_status_total{namespace=~\"$namespace\", deployment=~\"$deployment\", cache_status=~\".+\", route=~\"$route\", pod_name=~\"$pod\"}[$__rate_interval]))\n)\n",
     "legendFormat": "HIT"
    },
    {
     "expr": "100 * (\n  sum(rate(server_http_cache_status_total{namespace=~\"$namespace\", deployment=~\"$deployment\", cache_status=\"MISS\", route=~\"$route\", pod_name=~\"$pod\"}[$__rate_interval])) \n  /\n  sum(rate(server_http_cache_status_total{namespace=~\"$namespace\", deployment=~\"$deployment\", cache_status=~\".+\", route=~\"$route\", pod_name=~\"$pod\"}[$__rate_interval]))\n)\n",
     "legendFormat": "MISS"
    }
   ]
  },
  {
   "title": "Cache Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(nginx_http_cache_response_time_sum{namespace=~\"$namespace\", deployment=~\"$deployment\", route=~\"$route\", pod_name=~\"$pod\", cache_status=~\"$cache_status\"}[$__rate_interval])) by (cache_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Server Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (deployment) (\n  irate(server_http_request_bytes_received{namespace=\"$namespace\", deployment=~\"$deployment\", pod=~\"$pod\"}[$__rate_interval])\n)\n",
     "legendFormat": "in"
    },
    {
     "expr": "sum by (deployment) (\n  irate(server_http_request_bytes_sent{namespace=\"$namespace\", deployment=~\"$deployment\"}[$__rate_interval])\n)\n",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Upstream Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (deployment) (\n  irate(upstream_bytes_received{namespace=\"$namespace\", deployment=~\"$deployment\", pod=~\"$pod\"}[$__rate_interval])\n)\n",
     "legendFormat": "in"
    },
    {
     "expr": "sum by (deployment) (\n  irate(upstream_bytes_sent{namespace=\"$namespace\", deployment=~\"$deployment\"}[$__rate_interval])\n)\n",
     "legendFormat": "out"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Server Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (\n  server_http_connections{deployment=~\"$deployment\", namespace=~\"$namespace\", state=~\"active|writing|reading|waiting\", pod=~\"$pod\"}\n)\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response Time Total by (Route)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (route) (\n  rate(server_http_request_time_sum{namespace=~\"$namespace\", deployment=~\"$deployment\", route=~\"$route\", pod=~\"$pod\"}[$__rate_interval])\n)\n/\nsum by (route) (\n  rate(server_http_request_time_count{namespace=~\"$namespace\", deployment=~\"$deployment\", route=~\"$route\", pod=~\"$pod\"}[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server HTTP Methods",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (\nrate(server_http_methods{namespace=~\"$namespace\", deployment=~\"$deployment\", route=~\"$route\", pod=~\"$pod\"}[$__rate_interval])\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Server HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  irate(server_http_requests{namespace=\"$namespace\", deployment=~\"$deployment\", route=~\"$route\", pod=~\"$pod\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Server Request Time P50",
   "type": "heatmap",
   "description": "P50 (Mediana):\n\nDescrição: Este gráfico representa o valor da latência na mediana. Ou seja, 50% das requisições foram processadas mais rápido ou igual a este valor, e os outros 50% mais lentas. O P50 é uma boa medida para entender o desempenho central do sistema, pois não é influenciado por valores extremos.\nInterpretação: Ajuda a identificar o tempo de resposta típico do sistema para a maioria das requisições.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(server_http_request_time_bucket{namespace=\"$namespace\", deployment=\"$deployment\", route=~\"$route\", pod=~\"$pod\"}\n[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Server resquest Time P90",
   "type": "heatmap",
   "description": "P90 (Percentil 90):\n\nDescrição: Este gráfico mostra o valor da latência em que 90% das requisições foram processadas mais rápido ou igual a este tempo. Significa que os 10% mais lentos tiveram latências acima deste valor.\nInterpretação: É útil para entender o desempenho em relação às requisições mais lentas, ou seja, a \"cauda\" dos 10% mais lentos. Um aumento no P90 pode indicar problemas de desempenho que afetam uma parte significativa das requisições",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 76 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(server_http_request_time_bucket{namespace=\"$namespace\", deployment=\"$deployment\", route=~\"$route\", pod=~\"$pod\"}\n[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Server request Time P99",
   "type": "heatmap",
   "description": "P99 (Percentil 99):\n\nDescrição: Este gráfico representa o valor da latência em que 99% das requisições foram processadas mais rápido ou igual a este valor. Isso significa que apenas 1% das requisições são mais lentas do que o valor mostrado no gráfico.\nInterpretação: O P99 mostra a latência nos casos mais extremos do sistema, frequentemente usados para identificar outliers e entender o impacto dos piores casos no desempenho. A análise do P99 é importante para sistemas que precisam de alta confiabilidade, pois ele captura os momentos mais críticos.",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 76 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(server_http_request_time_bucket{namespace=\"$namespace\", deployment=\"$deployment\", route=~\"$route\", pod=~\"$pod\"}\n[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Server request Time P80",
   "type": "heatmap",
   "description": "**P80 (Percentil 80):**\n\n**Descrição:** Este gráfico representa o valor da latência em que 80% das requisições foram processadas mais rápido ou igual a este valor. Isso significa que 20% das requisições são mais lentas do que o valor mostrado no gráfico.\n\n**Interpretação:** O P80 mostra a latência em cenários comuns do sistema, focando no desempenho médio-superior. É frequentemente usado para entender a experiência da maioria dos usuários e identificar tendências gerais de desempenho, sem considerar os casos mais extremos como no P99. A análise do P80 é útil para balancear otimizações de desempenho sem priorizar outliers.",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(server_http_request_time_bucket{namespace=\"$namespace\", deployment=\"$deployment\", route=~\"$route\", pod=~\"$pod\"}\n[$__rate_interval])) by (le))",
     "legendFormat": "P80"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Backend Requests by http status",
   "type": "timeseries",
   "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  irate(upstream_requests{namespace=\"$namespace\", deployment=~\"$deployment\", route=~\"$route\", status!~\"total\", pod=~\"$pod\"}[$__rate_interval])\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Backend Response Time P50",
   "type": "heatmap",
   "description": "P50 (Mediana):\n\nDescrição: Este gráfico representa o valor da latência na mediana. Ou seja, 50% das requisições foram processadas mais rápido ou igual a este valor, e os outros 50% mais lentas. O P50 é uma boa medida para entender o desempenho central do sistema, pois não é influenciado por valores extremos.\nInterpretação: Ajuda a identificar o tempo de resposta típico do sistema para a maioria das requisições.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(upstream_response_time_bucket{namespace=\"$namespace\", deployment=\"$deployment\", route=~\"$route\", pod=~\"$pod\"}\n[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Backend response Time P90",
   "type": "heatmap",
   "description": "P90 (Percentil 90):\n\nDescrição: Este gráfico mostra o valor da latência em que 90% das requisições foram processadas mais rápido ou igual a este tempo. Significa que os 10% mais lentos tiveram latências acima deste valor.\nInterpretação: É útil para entender o desempenho em relação às requisições mais lentas, ou seja, a \"cauda\" dos 10% mais lentos. Um aumento no P90 pode indicar problemas de desempenho que afetam uma parte significativa das requisições",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 104 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(upstream_response_time_bucket{namespace=\"$namespace\", deployment=\"$deployment\", route=~\"$route\", pod=~\"$pod\"}\n[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Backend response Time P99",
   "type": "heatmap",
   "description": "P99 (Percentil 99):\n\nDescrição: Este gráfico representa o valor da latência em que 99% das requisições foram processadas mais rápido ou igual a este valor. Isso significa que apenas 1% das requisições são mais lentas do que o valor mostrado no gráfico.\nInterpretação: O P99 mostra a latência nos casos mais extremos do sistema, frequentemente usados para identificar outliers e entender o impacto dos piores casos no desempenho. A análise do P99 é importante para sistemas que precisam de alta confiabilidade, pois ele captura os momentos mais críticos.",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 104 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(upstream_response_time_bucket{namespace=\"$namespace\", deployment=\"$deployment\", route=~\"$route\", pod=~\"$pod\"}\n[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Backend response Time P80",
   "type": "heatmap",
   "description": "**P80 (Percentil 80):**\n\n**Descrição:** Este gráfico representa o valor da latência em que 80% das requisições foram processadas mais rápido ou igual a este valor. Isso significa que 20% das requisições são mais lentas do que o valor mostrado no gráfico.\n\n**Interpretação:** O P80 mostra a latência em cenários comuns do sistema, focando no desempenho médio-superior. É frequentemente usado para entender a experiência da maioria dos usuários e identificar tendências gerais de desempenho, sem considerar os casos mais extremos como no P99. A análise do P80 é útil para balancear otimizações de desempenho sem priorizar outliers.",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(upstream_response_time_bucket{namespace=\"$namespace\", deployment=\"$deployment\", route=~\"$route\", pod=~\"$pod\"}\n[$__rate_interval])) by (le))",
     "legendFormat": "P80"
    }
   ]
  },
  {
   "title": "Backend Response Time by (Route)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (route) (\n  rate(upstream_response_time_sum{namespace=~\"$namespace\", deployment=~\"$deployment\", route=~\"$route\", pod=~\"$pod\"}[$__rate_interval])\n) \n/ \nsum by (route) (\n  rate(upstream_response_time_count{namespace=~\"$namespace\", deployment=~\"$deployment\", route=~\"$route\", pod=~\"$pod\"}[$__rate_interval])\n)\n ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Derivada",
   "type": "timeseries",
   "description": "O gráfico mostra mede a direção da tendência da latência.\n\nPositiva: Latência aumentando.\nNegativa: Latência diminuindo.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "deriv(\n  sum by (route) (\n    rate(upstream_response_time_sum{namespace=~\"$namespace\", deployment=~\"$deployment\", route=~\"$route\"}[5m]) \n    / \n    rate(upstream_response_time_count{namespace=~\"$namespace\", deployment=~\"$deployment\", route=~\"$route\"}[5m])\n  )[15m:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "description": "O gráfico mostra a magnitude da variação. Da latência do tempo de resposta da api.\n\nValor em 0 significa latência perfeitamente estável (sem variação).\n\nQuanto maior o valor, mais imprevisível é a latência.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "stddev(\n  rate(upstream_response_time_sum{namespace=~\"$namespace\", deployment=~\"$deployment\", route=~\"$route\"}[1m]) \n  / \n  rate(upstream_response_time_count{namespace=~\"$namespace\", deployment=~\"$deployment\", route=~\"$route\"}[1m])\n) by (route)  * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}